---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup-socbehav, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results = 'markup', warning = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(stringr)
library(readr)
library(reshape2)
library(splines)

library(ggplot2)
library(ggpubr)
library(viridis)
library(ggdist)

library(brms)
library(rstan)
#library(cmdstanr)
library(tidybayes)
library(bayesplot)
library(randtoolbox)
library(posterior)


# Change wd
setwd("~/Users/MarienhagenJonathan/rlforaging")

```
```{r, directories-socbehav, include=FALSE}
if(!dir.exists("social/results")){dir.create("social/results")}
if(!dir.exists("social/results/behav")){dir.create("social/results/behav")}

```

```{r, data-socbehav, echo=TRUE}
# Read data
path = "~/Users/MarienhagenJonathan/thesisvc/data/data_discrete_1s.csv"
d = read.csv(path,colClasses = c(rep(NA, 8), rep("character", 2), rep(NA, 4)))

# Set player id unique across sessions
d = d %>% mutate(id = (session - 1) * 5  + player) %>%
  mutate(id = factor(id, levels = c(1:max(id)))) %>%
  mutate(decision = correct) %>% mutate(reward = catch) %>% mutate(nplayers = 5) %>%
  mutate(time = time.rounded)

d = d %>%
  mutate(max.fac = factor(max.fac, levels = c(1:3))) %>%
  mutate(ratio.fac = factor(ratio.fac, levels = c(1:4))) %>%
  mutate(social.fac = factor(social.fac, levels = c(1:3))) %>%
  mutate(cond = interaction(max.fac, ratio.fac, social.fac)) %>%
  mutate(session = factor(session, levels=1:max(session)))

```

# Accuracy 
```{r, acc}
# Set priors
formula = bf(decision ~ 0 + cond + (1|session) + (1|id)) # hierarchical

get_prior(formula = formula, data = d, family = bernoulli(link = "logit"))

priors = c(prior(normal(0, 1.5), class = b),
           prior(normal(0, .5), class = sd))

# Fit model
acc = brm(formula = formula, prior = priors,
          data = d, family = bernoulli(link = logit),
          chains = 4, cores = 4,
          iter=3000, warmup=2000, refresh=10)

acc.draws = as_draws_df(acc)

diagnostics = data.frame(
  bulk_ess = apply(acc.draws, 2, posterior::ess_bulk),
  tail_ess = apply(acc.draws, 2, posterior::ess_tail),
  rhat = apply(acc.draws, 2, posterior::rhat)
  )

dignostics = sapply(1:ncol(acc.draws), function(x) {
  column <- acc.draws[x, ]
  c(bulk_ess = ess_bulk(column), tail_ess = ess_tail(column))
})

write.csv(diagnostics, paste("social", "results", "behav", "behav.diagnostics.csv", sep = "/"), row.names = TRUE)

prior_summary(acc)
acc

saveRDS(acc, paste("social/results/behav", "acc.rds", sep="/"))

# Plot posterior means + hdis 
ratio.labs = paste("Catch Ratio:", sort(unique(d$ratio)))
names(ratio.labs) = sort(unique(d$ratio.fac))

max.labs = paste("Max Catch", sort(unique(d$max)))
names(max.labs) = sort(unique(d$max.fac))

facet.labeller = labeller(ratio.fac = ratio.labs, max.fac = max.labs)

acc.draws = tidy_draws(acc)
write.csv(acc.draws, row.names = F, file = "social/results/behav/acc_draws_wide.csv")

acc.draws = acc.draws %>% dplyr::select(contains(c("b"))) %>%
  #mutate(b_cond1.1.1 = 0) %>%
  mutate(draw = row_number()) %>%
  #pivot_longer(contains("b_cond"), names_to = "cond", values_to = "condoffset") %>%
  #mutate(post = b_Intercept + condoffset) %>%
  pivot_longer(-draw, names_to = "cond", values_to = "cond_intercept") %>%
  #mutate(post = inv_logit_scaled(post)) %>%
  #mutate(cond_intercept = inv_logit_scaled(cond_intercept)) %>%
  mutate(cond = gsub("b_cond", "", cond)) %>%
  separate(cond, into = c("max.fac", "ratio.fac", "social.fac"))
write.csv(acc.draws, row.names = F, file = "social/results/behav/acc_draws_long.csv")


acc.draws = acc.draws %>% 
  mutate(cond_intercept = inv_logit_scaled(cond_intercept)) %>%
  group_by(max.fac, ratio.fac, social.fac) %>%
  mean_hdi(cond_intercept, .width = .9) %>%
  mutate(max.fac = factor(max.fac, levels=1:3))


d.plot = d %>%
  group_by(session, trial, id, duration, max.fac, ratio.fac, social.fac) %>%
  reframe(acc = sum(decision) ) %>%
  mutate(acc = acc / (duration + 1)) %>%
  select(-c(session, trial, duration)) %>%
  pivot_wider(names_from = id, names_prefix = "id", values_from = acc)

plot.data = left_join(acc.draws, d.plot, by = join_by(max.fac, ratio.fac, social.fac))
write.csv(plot.data, file = paste("social/results/behav/acc.csv"))

p = ggplot() +
  geom_point(data = d.plot,
             aes(x=social.fac,col=social.fac, y=acc),
              position = position_jitter(width = .15),
            size=2, shape=21, fill="white") +
  geom_line(data = acc.draws, 
                  aes(x=social.fac, y=cond_intercept, group = interaction(max.fac, ratio.fac))) +
  geom_pointrange(data = acc.draws, 
                  aes(x=social.fac, y=cond_intercept, ymin=.lower, ymax=.upper,
                      fill=social.fac),
                  shape=21, col="black", size=.75) +
  geom_hline(yintercept = .5, lty=2) +
  scale_y_continuous(name = "Accuracy") +
  scale_x_discrete(name = "Condition", labels = c("Alone", "No Catches", "Catches")) +
  scale_fill_viridis(name = "Condition", labels = c("Alone", "No Catches", "Catches"),
                      discrete = T, end = .8) +
  scale_color_viridis(name = "Condition", labels = c("Alone", "No Catches", "Catches"),
                      discrete = T, end = .8) +
  #scale_x_discrete(expand = c(0.15, 0)) +
  theme_linedraw(base_size = 8) +
  theme(legend.position = "none") +
  facet_grid(ratio.fac ~ max.fac, labeller = facet.labeller)
p
ggsave(plot = p, dpi=300, width = 6.5, height = 6.5, units = "in",
       filename = paste("social/results/behav", "acc.png", sep = "/"))


```

<!-- # Accuracy over time -->
<!-- ```{r, acc-time} -->
<!-- # Use cmdstanr -->
<!-- options(brms.backend = "cmdstanr") -->

<!-- # Output dir -->
<!-- outdir = paste("social/results/behav", "cmdstanout", sep="/") -->
<!-- if(!dir.exists(outdir)){dir.create(outdir)} -->

<!-- # Log file -->
<!-- log.txt = paste("social/results/behav", "cmdstanout", "acctime_fixed_log.txt", sep="/") -->

<!-- # Sink -->
<!-- sink(log.txt, append = T) -->


<!-- #formula = bf(decision ~ mo(time) * cond  + (1|session) + (1|id)) -->
<!-- formula = bf(decision ~ mo(time) * cond) -->

<!-- acctime = brm(data = d, family = bernoulli(link = "logit"), -->
<!--          formula = formula, -->
<!--          chains = 4, cores = 4, iter = 1000, warmup = 500, refresh=10, -->
<!--          output_dir = outdir) -->
<!-- saveRDS(acctime, paste("social/results/behav", "acctime.rds", sep="/")) -->
<!-- sink() -->


<!-- plot(conditional_effects(acctime)) -->

<!-- draws = tidy_draws(m2) -->


<!-- # Intercept and cond at t == 0 -->
<!-- cond = draws %>%  -->
<!--   # Main effect of condition -->
<!--   mutate("b_cond1.1.1" = 0) %>% -->
<!--   select(contains(c(".chain", ".iteration", ".draw", "b_cond", "Intercept"))) %>% -->
<!--   pivot_longer(contains("b_cond"), names_to = "cond", values_to = "b_cond") %>% -->
<!--   mutate(cond = gsub("b_cond", "", cond)) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac")) %>%  -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, social.fac) %>%  -->
<!--   reframe(b_cond = Intercept + b_Intercept + b_cond)  -->


<!-- # Sum simplex time -->
<!-- motime = draws %>% -->
<!--   select(contains(c(".chain", ".iteration", ".draw", "simo_motime1", "bsp_motime"))) %>% select(!contains("bsp_motime:cond")) %>% -->
<!--   mutate("simo_motime1[0]" = 0) %>% -->
<!--   pivot_longer(!contains(c(".chain", ".iteration", ".draw", "bsp_motime")), names_to = "time", values_to = "simplex_time") %>% -->
<!--   mutate(time = gsub("simo_motime1", "", time)) %>% -->
<!--   mutate(time=parse_number(time)) %>% -->
<!--   #mutate(time=as.integer(time + 1)) %>% -->
<!--   group_by(.chain, .iteration, .draw, bsp_motime) %>% -->
<!--   arrange(.chain, .iteration, .draw, bsp_motime, time) %>% -->
<!--   mutate(simplex_time = cumsum(simplex_time)) %>% -->
<!--   mutate(duration = max(time)) %>% -->
<!--   group_by(.chain, .iteration, .draw, time) %>% -->
<!--   reframe(motime = bsp_motime * duration * simplex_time) -->

<!-- # Check -->
<!-- # post = merge(cond, motime) %>% -->
<!-- #   mutate(decision = b_cond + motime) %>% -->
<!-- #   group_by(max.fac, ratio.fac, social.fac, time) %>% -->
<!-- #   reframe(decision = mean(inv_logit_scaled(decision))) -->
<!-- # post %>% -->
<!-- #   ggplot(aes(x=time, y=decision, col=max.fac)) + geom_line() + -->
<!-- #   ylim(0, 1) -->


<!-- # Sum simplex timecond -->
<!-- motimecond = draws %>% -->
<!--   select(contains(c(".chain", ".iteration", ".draw", "simo_motime:cond"))) %>% -->
<!--   cbind( -->
<!--     matrix(0, nrow = nrow(draws), ncol = length(paste0("simo_motime:cond1.1.1[", 0:(max(d$time)), "]"))) %>% as.data.frame() %>% -->
<!--       `colnames<-`(paste0("simo_motime:cond1.1.1[", 0:(max(d$time)), "]")) -->
<!--     ) %>% -->
<!--   cbind( -->
<!--     matrix(0, nrow = nrow(draws), ncol=length(paste0("simo_motime:cond", sort(unique(d$cond)), "[", 0, "]"))) %>% as.data.frame() %>% -->
<!--       `colnames<-`(paste0("simo_motime:cond", sort(unique(d$cond)), "[", 0, "]")) -->
<!--   ) %>% -->
<!--   pivot_longer(!contains(c(".chain", ".iteration", ".draw")), names_to = "time_cond", values_to = "simplex_timecond") %>% -->
<!--   mutate(time_cond = gsub("simo_motime:cond", "", time_cond)) %>% -->
<!--   mutate(cond = sub("\\[.*", "", time_cond)) %>% -->
<!--   mutate(time = parse_number(gsub(".*\\[", "", time_cond))) %>% -->
<!--   #mutate(time = time + 1) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac")) %>% -->
<!--   mutate(social.fac = ifelse(social.fac == "11", "1", ifelse(social.fac == "21", "2", social.fac))) %>% ################################### -->
<!--   select(-time_cond) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, social.fac) %>% -->
<!--   arrange(.chain, .iteration, .draw, max.fac, ratio.fac, social.fac, time) %>% -->
<!--   mutate(simplex_timecond = cumsum(simplex_timecond))  -->

<!-- # B timecond -->
<!-- btimecond = draws %>% select(contains(c(".chain", ".iteration", ".draw", "bsp_motime:cond"))) %>% -->
<!--   mutate("bsp_motime:cond1.1.1" = 0) %>% -->
<!--   pivot_longer(!contains(c(".chain", ".iteration", ".draw")), names_to = "cond", values_to = "b_timecond") %>% -->
<!--   mutate(cond = gsub("bsp_motime:cond", "", cond)) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac"))  -->

<!-- motimecond = merge(motimecond, btimecond) %>%  -->
<!--   mutate(duration = max(time)) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, social.fac, time) %>% -->
<!--   reframe(motimecond = b_timecond * duration * simplex_timecond) -->




<!-- post = merge(merge(cond, motime), motimecond) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, social.fac, time) %>%  -->
<!--   reframe(decision = b_cond + motime + motimecond)  -->



<!-- #### Plot #### -->
<!-- ratio.labs = paste("Yield Ratio:", sort(unique(d$ratio))) -->
<!-- names(ratio.labs) = sort(unique(post$ratio.fac)) -->

<!-- max.labs = paste("Maximum Yield", sort(unique(d$max))) -->
<!-- names(max.labs) = sort(unique(post$max.fac)) -->

<!-- facet.labeller = labeller(ratio.fac = ratio.labs, max.fac = max.labs) -->

<!-- # Plot asocial learning curve -->
<!-- plot.data = post %>%  -->
<!--   ungroup() %>% -->
<!--   group_by(max.fac, ratio.fac, social.fac, time) %>%  -->
<!--   mean_hdi(decision, .width = .9) %>% -->
<!--   mutate_at(vars(decision, .lower, .upper), inv_logit_scaled) -->

<!-- p1 = plot.data %>% filter(social.fac == 1) %>% -->
<!--   ggplot(aes(x=time, y=decision, ymin=.lower, ymax=.upper, col=max.fac, fill=max.fac)) + -->
<!--   geom_line(lwd=1) + -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   geom_hline(yintercept =  0.5, lty=2) + -->
<!--   labs(x="Time", y="p") + -->
<!--   scale_color_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8)+ -->
<!--   scale_fill_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8) + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         legend.position = "top", -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm")) + -->
<!--   facet_wrap( ~  ratio.fac, ncol=4, labeller = facet.labeller) -->

<!-- # Plot contrast -->
<!-- # Plot asocial learning curve -->
<!-- plot.data = post %>%  -->
<!--   ungroup() %>% -->
<!--   mutate_at(vars(decision), inv_logit_scaled) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, time) %>%  -->
<!--   arrange(.chain, .iteration, .draw, max.fac, ratio.fac, time, social.fac) %>% -->
<!--   #mutate(contrast = decision[which(social.fac==2)] - decision[which(social.fac == 1)]) -->
<!--   reframe(contrast = diff(decision)) %>% -->
<!--   group_by(max.fac, ratio.fac, time) %>% -->
<!--   mean_hdi(contrast, .width = .9) -->

<!-- p2 = plot.data %>%  -->
<!--   ggplot(aes(x=time, y=contrast, ymin=.lower, ymax=.upper, col=max.fac, fill=max.fac)) + -->
<!--   geom_line(lwd=1) + -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   geom_hline(yintercept =  0, lty=2) + -->
<!--   labs(x="Time", y=bquote(paste(Delta, "p" ))) + -->
<!--   scale_color_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8)+ -->
<!--   scale_fill_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8) + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         legend.position = "top", -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm")) + -->
<!--   facet_wrap( ~  ratio.fac, ncol=4, labeller = facet.labeller) -->


<!-- p = ggarrange(p1, p2, nrow = 2, -->
<!--               labels = c("a", "b"), font.label = list(size=rel(30)), common.legend = T, legend = "top") -->
<!-- ggexport(p, width = 2560, height = 1440, -->
<!--          filename = paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "modacctime.jpeg", sep="/")) -->



<!-- # Plot asocial learning curve contrast relative to max == 1 -->
<!-- plot.data = post %>% ungroup() %>% -->
<!--   mutate(decision = inv_logit_scaled(decision)) %>% -->
<!--   group_by(.chain, .iteration, .draw, ratio.fac, social.fac, time) %>%  -->
<!--   mutate(contrast = ifelse(max.fac == 2, decision[which(max.fac == 2)] - decision[which(max.fac==1)], -->
<!--                            ifelse(max.fac == 3, decision[which(max.fac==3)] - decision[which(max.fac == 1)], NA))) %>% -->
<!--   drop_na(contrast) %>% -->
<!--   group_by(ratio.fac, max.fac, time) %>% -->
<!--   mean_hdi(contrast, .width = .9) -->

<!-- plot.data %>% -->
<!--   ggplot(aes(x=time, y=contrast, ymin=.lower, ymax=.upper, col=max.fac, fill=max.fac)) + -->
<!--   geom_line() +  -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   facet_wrap( ~  ratio.fac) -->

<!-- # Plot asocial learning curve contrast relative to max == 2 -->
<!-- plot.data = post %>% ungroup() %>% -->
<!--   mutate(decision = inv_logit_scaled(decision)) %>% -->
<!--   group_by(.chain, .iteration, .draw, ratio.fac, social.fac, time) %>%  -->
<!--   mutate(contrast = ifelse(max.fac == 3, decision[which(max.fac == 3)] - decision[which(max.fac==2)], NA)) %>% -->
<!--   drop_na(contrast) %>% -->
<!--   group_by(ratio.fac, max.fac, time) %>% -->
<!--   mean_hdi(contrast, .width = .9) -->

<!-- plot.data %>% -->
<!--   ggplot(aes(x=time, y=contrast, ymin=.lower, ymax=.upper, col=max.fac, fill=max.fac)) + -->
<!--   geom_line() +  -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   facet_wrap( ~  ratio.fac) -->

<!-- # Plot asocial learning curve contrast to ratio == 1 -->
<!-- plot.data = post %>% ungroup() %>% -->
<!--   mutate(decision = inv_logit_scaled(decision)) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, social.fac, time) %>%  -->
<!--   mutate(contrast = ifelse(ratio.fac == 2, decision[which(ratio.fac == 2)] - decision[which(ratio.fac==1)], -->
<!--                            ifelse(ratio.fac == 3, decision[which(ratio.fac == 3)] - decision[which(ratio.fac==1)],  -->
<!--                                   ifelse(ratio.fac == 4, decision[which(ratio.fac == 4)] - decision[which(ratio.fac==1)], NA)))) %>% -->
<!--   drop_na(contrast) %>% -->
<!--   group_by(ratio.fac, max.fac, time) %>% -->
<!--   mean_hdi(contrast, .width = .9) -->

<!-- plot.data %>% -->
<!--   ggplot(aes(x=time, y=contrast, ymin=.lower, ymax=.upper, col=ratio.fac, fill=ratio.fac)) + -->
<!--   geom_line() +  -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   facet_wrap( ~  max.fac) -->


<!-- # Contrast between social conditions -->
<!-- contrast = post %>% ungroup() %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac, time) %>%  -->
<!--   arrange(.chain, .iteration, .draw, max.fac, ratio.fac, time, social.fac) %>% -->
<!--   mutate(decision = inv_logit_scaled(decision)) %>% -->
<!--   mutate(contrast = diff(decision)) %>% -->
<!--   group_by(max.fac, ratio.fac, time) %>% -->
<!--   mean_hdi(contrast, .width = .9) -->


<!-- contrast%>% -->
<!--   ggplot(aes(x=time, y=contrast, ymin=.lower, ymax=.upper)) + -->
<!--   geom_line() +  -->
<!--   geom_lineribbon(alpha=.5) + -->
<!--   facet_grid(ratio.fac ~  max.fac) -->

<!-- # Compute contrasts for table -->
<!-- bmotime = draws %>% -->
<!--   select(contains(c(".chain", ".iteration", ".draw", "bsp_motime"))) %>% -->
<!--   mutate("bsp_motime:cond1.1.1" = 0) %>% -->
<!--   pivot_longer(contains("cond"), names_to = "cond", values_to = "cond_offset") %>% -->
<!--   mutate(cond = gsub("bsp_motime:cond", "", cond)) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac"))  -->

<!-- post = bmotime %>% -->
<!--   mutate(post = bsp_motime + cond_offset) %>% -->
<!--   group_by(max.fac, ratio.fac, social.fac) %>% -->
<!--   mean_hdi(post, .width = .9) %>% -->
<!--   filter(social.fac == 1) %>% -->
<!--   mutate_at(vars(post, .lower, .upper), round, digits=3) -->

<!-- con = bmotime %>% -->
<!--   mutate(post = bsp_motime + cond_offset) %>% -->
<!--   group_by(.chain, .iteration, .draw, max.fac, ratio.fac) %>% -->
<!--   reframe(contrast = post[which(social.fac == 2)] - post[which(social.fac == 1)]) %>% -->
<!--   group_by(max.fac, ratio.fac) %>% -->
<!--   mean_hdi(contrast, .width = .9) %>% -->
<!--   mutate_at(vars(contrast, .lower, .upper), round, digits=3) -->



<!-- ``` -->

<!-- # Accuracy over time -- Stan version -->
<!-- ```{r, acctime-stan} -->
<!-- # Put experimental data in list -->
<!-- stan.data = with(d, list( -->
<!--   OBSERVATIONS=nrow(d), -->
<!--   SESSIONS=max(unique(session)), session=session, -->
<!--   TRIALS=max(unique(trial)), trial=trial, -->
<!--   MAXIMUM=max(unique(max.fac)), maximum=max.fac, -->
<!--   RATIO=max(unique(ratio.fac)), ratio=ratio.fac, -->
<!--   SOCIAL=max(unique(social.fac)), social=social.fac, -->
<!--   PLAYERS=unique(nplayers), -->
<!--   ID=max(id), id=id, -->
<!--   TIMES=max(unique(time.rounded)), time=time.rounded, -->
<!--   DECISIONS=length(unique(decision)), decision=decision,  -->
<!--   REWARDS=length(unique(reward)), reward=reward -->
<!-- )) -->

<!-- acctime = stan(file = "~/Users/MarienhagenJonathan/rlforaging/social/code/stan/acctime_social.stan", data = stan.data, -->
<!--                chains = 4, cores = 4, iter = 2000, warmup = 1000, refresh=10) -->

<!-- acctime.draws = tidy_draws(acctime) -->
<!-- acctime.draws = apply(acctime.draws, 2, mean) -->

<!-- results = data.frame() -->
<!-- for(m in 1:max(d$max.fac)){ -->
<!--   print(m) -->
<!--   for (r in 1:max(d$ratio.fac)) { -->
<!--     print(r) -->
<!--     for (t in 1:max(d$duration)){ -->
<!--       alpha = paste0("alpha", "[", m, ",", r, "]") -->
<!--       b_time_max = paste0("b_time_max", "[", m, ",", r, "]") -->
<!--       b_time = paste0("b_time", "[", m, ",", r, ",", 1:t, "]") -->
<!--       acc = unname(inv_logit_scaled(acctime.draws[, alpha] + acctime.draws[, b_time_max] * apply(acctime.draws[, b_time], 1, sum))) -->
<!--       results.sub = data.frame(max.fac = m, ratio.fac = r, time = t, acc=acc) %>%  -->
<!--         group_by(max.fac, ratio.fac, time) %>% mean_hdi(acc) -->
<!--       results = rbind(results, results.sub) -->
<!--     } -->
<!--   } -->
<!-- } -->


<!-- results %>% group_by(max.fac, ratio.fac) mean_hdi() -->

<!-- results %>% -->
<!--   ggplot(aes(x=time, y=acc, ymin=.lower, ymax=.upper)) + geom_ribbon(alpha=.75) + geom_line() +   facet_grid(ratio.fac ~ max.fac) -->


<!-- ``` -->


<!-- # Accuracy over time -- Spline version -->
<!-- ```{r, acctime-spline} -->
<!-- nknots = 10 -->
<!-- knotlist = seq(from = 0, to=105, length=nknots) -->
<!-- B = bs(d$time, knots = knotlist[-c(1, length(knotlist))], intercept = F, degree = 3) -->

<!-- brm.data = d %>% mutate(cond=interaction(max.fac, ratio.fac, social.fac)) %>% mutate(B = B)  -->

<!-- acctime <-  -->
<!--   brm(data = brm.data, -->
<!--       family = bernoulli, -->
<!--       decision ~ 1 + B * cond, -->
<!--       iter = 2000, warmup = 1000, chains = 4, cores = 4, refresh=10) -->

<!-- f <- fitted(acctime) -->

<!-- f %>%  -->
<!--   data.frame() %>%  -->
<!--   bind_cols(ratio=d$ratio, max=d$max, social.fac=d$social.fac, time=d$time) %>% -->
<!--   ggplot(aes(x = time, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill=social.fac)) +  -->
<!--   geom_vline(xintercept = knotlist, color = "white", alpha = 1/2) + -->
<!--   geom_hline(yintercept = .5, color = "white", linetype = 2) + -->
<!--   geom_line() + -->
<!--   #geom_ribbon() + -->
<!--   labs(x = "Time", -->
<!--        y = "Accuracy") + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm"))  + -->
<!--   facet_grid(ratio ~ max) -->

<!-- ``` -->
<!-- # Switch rate  -->
<!-- ```{r, switch} -->
<!-- d = d %>% -->
<!--   group_by(session, trial, id) %>% -->
<!--   arrange(session, trial, id, time) %>% -->
<!--   mutate(switch = ifelse(decision != lag(decision), 1, 0)) %>% -->
<!--   drop_na(switch) -->

<!-- # Formula -->
<!-- formula = bf(switch ~ cond +  (1|session) + (1|id)) -->

<!-- # Fit model -->
<!-- m3 = brm(formula = formula, data = d, family = bernoulli(link = logit), -->
<!--           chains = 4, cores = 4, -->
<!--           iter=4000, warmup=2000, refresh=200) -->


<!-- m3 -->

<!-- saveRDS(m3, paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "switch.rds", sep="/")) -->

<!-- # Plot posterior means + hdis for asocial condition -->
<!-- m3.draws = tidy_draws(m3) %>% dplyr::select(contains(c("b"))) %>% -->
<!--   mutate(b_cond1.1.1 = 0) %>% -->
<!--   mutate(sample = row_number()) %>% -->
<!--   pivot_longer(contains("b_cond"), names_to = "cond", values_to = "condoffset") %>% -->
<!--   mutate(post = b_Intercept + condoffset) %>% -->
<!--   mutate(post = inv_logit_scaled(post)) %>% -->
<!--   mutate(cond = gsub("b_cond", "", cond)) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac")) %>% -->
<!--   group_by(max.fac, ratio.fac, social.fac) %>% -->
<!--   mean_hdi(post, .width = .9) %>% -->
<!--   mutate_at(vars(post, .lower, .upper), round, digits=3) %>% -->
<!--   mutate(max.fac = factor(max.fac, levels=1:3)) -->

<!-- p1 = m3.draws %>% filter(social.fac == 1) %>% -->
<!--   ggplot(aes(x=ratio.fac, col=max.fac)) +  -->
<!--   geom_pointrange(aes(y=post, ymin=.lower, ymax=.upper),  -->
<!--                   position = position_dodge(width = .3), size=1, lwd=1) +  -->
<!--   labs(y="s") + -->
<!--   scale_x_discrete(name = "Yield Ratio", labels = c("0.50", "0.65", "0.80", "0.95")) + -->
<!--   scale_color_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8) + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm"))  -->
<!-- p1 -->

<!-- p2 = m3.draws %>% -->
<!--   ggplot(aes(x=ratio.fac, col=max.fac, shape=as.factor(social.fac))) +  -->
<!--   geom_pointrange(aes(y=post, ymin=.lower, ymax=.upper),  -->
<!--                   position = position_dodge(width = .3), size=1, lwd=1) +  -->
<!--   labs(y="s") + -->
<!--   scale_x_discrete(name = "Yield Ratio", labels = c("0.50", "0.65", "0.80", "0.95")) + -->
<!--   scale_color_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8) + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm"))  -->
<!-- p2 -->


<!-- # Plot contrast social setting -->
<!-- con = tidy_draws(m3) %>% dplyr::select(contains(c("b"))) %>% -->
<!--   mutate(b_cond1.1.1 = 0) %>% -->
<!--   mutate(sample = row_number()) %>% -->
<!--   pivot_longer(contains("b_cond"), names_to = "cond", values_to = "condoffset") %>% -->
<!--   mutate(post = b_Intercept + condoffset) %>% -->
<!--   mutate(post = inv_logit_scaled(post)) %>% -->
<!--   mutate(cond = gsub("b_cond", "", cond)) %>% -->
<!--   separate(cond, into = c("max.fac", "ratio.fac", "social.fac")) %>% -->
<!--   group_by(sample, max.fac, ratio.fac) %>% -->
<!--   arrange(sample, max.fac, ratio.fac, social.fac) %>% -->
<!--   reframe(contrast = diff(post)) %>% -->
<!--   group_by(max.fac, ratio.fac) %>% -->
<!--   mean_hdi(contrast, .width = .9) %>% -->
<!--   mutate_at(vars(contrast, .lower, .upper), round, digits=3) %>% -->
<!--   mutate(max.fac = factor(max.fac, levels=1:3)) -->


<!-- p3 = con %>% -->
<!--   ggplot(aes(x=ratio.fac, col=max.fac)) +  -->
<!--   geom_pointrange(aes(y=contrast, ymin=.lower, ymax=.upper),  -->
<!--                   position = position_dodge(width = .3), size=1, lwd=1) +  -->
<!--   geom_hline(yintercept = 0, lty=2) + -->
<!--   labs(x="Yield Ratio", y=bquote(paste(Delta, "s" ))) + -->
<!--   scale_color_viridis(name = "Maximum Yield", labels = c("0.50", "0.70", "0.90"), -->
<!--                       discrete = T, end = .8) + -->
<!--   scale_x_discrete(name = "Yield Ratio", labels = c("0.50", "0.65", "0.80", "0.95")) + -->
<!--   theme_linedraw(base_size = 11) + -->
<!--   theme(text = element_text(size=rel(5)), -->
<!--         strip.text.x = element_text(size=rel(7)), -->
<!--         strip.text.y = element_text(size=rel(7)),  -->
<!--         axis.text.x = element_text(size=rel(7)), -->
<!--         axis.title.x = element_text(size=rel(7)), -->
<!--         axis.text.y = element_text(size=rel(7)), -->
<!--         axis.title.y = element_text(size=rel(7)), -->
<!--         legend.text = element_text(size=rel(7)),  -->
<!--         legend.title = element_text(size=rel(7)), -->
<!--         plot.title = element_text(hjust = 0.5, size = rel(8)), -->
<!--         plot.margin = margin(1,1,1,1, "cm"))  -->
<!-- p3 -->

<!-- # p = ggarrange(p1, p3, nrow = 2, labels = c("a", "b"),  -->
<!-- #               font.label = list(size=rel(30)), common.legend = T, legend = "right") -->
<!-- p = ggarrange(p1, p3, nrow = 2, labels = c("a", "b"), font.label = list(size=rel(30)), common.legend = T, legend = "top") -->
<!-- p -->
<!-- ggexport(p, width = 2560, height = 1440,  -->
<!--          filename = paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "modswitch.jpeg", sep = "/")) -->

<!-- ``` -->

<!-- # Switch rate over time -->
<!-- ```{r, switch-time} -->
<!-- d = d %>% -->
<!--   group_by(session, trial, id) %>% -->
<!--   arrange(session, trial, id, time) %>% -->
<!--   mutate(switch = ifelse(decision == lag(decision), 1, 0)) %>% -->
<!--   drop_na(switch) -->

<!-- # Use cmdstanr -->
<!-- options(brms.backend = "cmdstanr") -->

<!-- # Output dir -->
<!-- outdir = paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "cmdstanout_switchtime", sep="/") -->
<!-- if(!dir.exists(outdir)){dir.create(outdir)} -->

<!-- # Log file -->
<!-- log.txt = paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "cmdstanout_switchtime", "switchtime_log.txt", sep="/") -->

<!-- # Sink -->
<!-- sink(log.txt, append = T) -->


<!-- formula = bf(switch ~ mo(time) * cond + (1|session) + (1|id)) -->


<!-- m4 = brm(data = d, family = bernoulli(link = "logit"), -->
<!--          formula = formula, -->
<!--          chains = 4, cores = 4, iter = 2000, warmup = 1000, refresh=1, -->
<!--          output_dir = outdir) -->
<!-- saveRDS(m4, paste("~/Users/MarienhagenJonathan/thesisvc/social/results/behav", "switchtime.rds", sep="/")) -->
<!-- sink() -->
<!-- ``` -->