---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup-modcomp, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results = 'markup', warning = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(stringr)

library(ggplot2)
library(ggpubr)
library(viridis)

library(rstan)
library(loo)
library(tidybayes)
library(bayesplot)
library(randtoolbox)

# Source functions
setwd("~/Users/MarienhagenJonathan/rlforaging")

source("social/code/functions/softmax.R")
source("social/code/functions/diagnostics.plot.R")
source("social/code/functions/getmodels.R")



```
```{r, dir-modcomp, include=FALSE}
if(!dir.exists("social/results")){dir.create("social/results")}
if(!dir.exists("social/results/modelcomp_decpayoff")){dir.create("social/results/modelcomp_decpayoff")}

if(!dir.exists("social/results/modelcomp_decpayoff/full_nonadaptive")){dir.create("social/results/modelcomp_decpayoff/full_nonadaptive")}
if(!dir.exists("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics")){dir.create("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics")}
if(!dir.exists("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics/detailed")){dir.create("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics/detailed")}

# if(!dir.exists("social/results/modelcomp_decpayoff_sub")){dir.create("social/results/modelcomp_decpayoff_sub")}
# if(!dir.exists("social/results/modelcomp_decpayoff_sub/diagnostics")){dir.create("social/results/modelcomp_decpayoff_sub/diagnostics")}


```

# Experimental data
```{r, data-modelcomp_dec, echo =TRUE, eval=TRUE}
# Read data
path = "~/Users/MarienhagenJonathan/thesisvc/data/data_discrete_1s.csv"
d = read.csv(path,colClasses = c(rep(NA, 8), rep("character", 2), rep(NA, 4)))

# Rename and add player id that is unique across sessions
d = d %>% mutate(decision = correct) %>% mutate(reward = catch) %>% mutate(nplayers = 5) %>%
  mutate(id = (session - 1) * 5  + player) %>% select(-player)

# Get socials trials with both observed decisions and observed payoffs
d = d %>% filter(social.fac == 3)

# Compute observed decisions and observed payoffs
d=d %>%
  arrange(session, trial, id, time.rounded) %>%
  # Observed decisions
  group_by(session, trial, id) %>%
  mutate(decision.lag = lag(decision)) %>%
  group_by(session, trial, time.rounded) %>%
  mutate(obs.dec.2 = sum(decision.lag)) %>% # Number of individuals choosing higher yielding patch
  ungroup() %>%
  mutate(obs.dec.2 = obs.dec.2 - decision.lag) %>% # Subtract individual's own choice
  ungroup() %>%
  mutate(obs.dec.1 = nplayers - 1 - obs.dec.2) %>% # Lower yielding patch
  mutate(obs.dec.1.norm = obs.dec.1 / (nplayers-1), obs.dec.2.norm = obs.dec.2 / (nplayers-1)) %>% # normalize
  relocate(obs.dec.1, obs.dec.2,.after = nplayers) %>%
  # Observed payoffs
  arrange(session, trial, id, time.rounded) %>%
  group_by(session, trial, id) %>%
  mutate(reward.lag = lag(reward)) %>% 
  group_by(session, trial, time.rounded, decision.lag) %>%
  mutate(obs.rew = sum(reward.lag)) %>% # Rewards obtained by all players at each patch
  group_by(session, trial, id) %>%
  mutate(obs.rew = obs.rew - reward.lag) %>% # Minus rewards obtained by individuals themselves
  mutate(obs.rew.norm = ifelse(decision.lag == 0, obs.rew / obs.dec.1, obs.rew / obs.dec.2)) %>% # normalize
  mutate(decision = decision + 1) %>% # Transform [0, 1] to [1, 2]
  arrange(session, trial, id, time.rounded) 
  

# Account for missing social information for stan
d = d %>% 
  mutate(obs.dec.1.norm = ifelse(is.na(obs.dec.1.norm), 100, obs.dec.1.norm)) %>%
  mutate(obs.dec.2.norm = ifelse(is.na(obs.dec.2.norm), 100, obs.dec.2.norm)) %>%
  mutate(obs.rew.norm=ifelse(is.na(obs.rew.norm), 100, obs.rew.norm))

# Put experimental data in list
stan.data.d = with(d, list(
  OBSERVATIONS=nrow(d),
  SESSIONS=max(unique(session)), session=session,
  TRIALS=max(unique(trial)), trial=trial,
  MAXIMUM=length(unique(max.fac)), maximum=max.fac,
  RATIO=length(unique(ratio.fac)), ratio=ratio.fac,
  PLAYERS=unique(nplayers),
  ID=max(id), id=id,
  TIMES=max(unique(time.rounded)), time=time.rounded,
  DECISIONS=length(unique(decision)), decision=decision, 
  obsdec=cbind(obs.dec.1.norm, obs.dec.2.norm),
  obsrew=obs.rew.norm,
  REWARDS=length(unique(reward)), reward=reward
))
```


# MCMC Settings
```{r, mcmc-modelcomp_dec, echo=TRUE, results='markup'}
# MCMC 
chains = 4
cores = 4
iter = 4000
warmup = 2000
refresh = 100
```


# Model comparison with all (non-adaptive) models
```{r, run-modelcomp_decpay_full_nonadaptive, echo=TRUE, eval=TRUE}
if(!file.exists(paste("social/results/modelcomp_decpayoff/full_nonadaptive", "modelcomp_decpayoff_full_nonadaptive.Rdata", sep = "/"))){
  
  # Get models
  models = getmodels(hierarch = T)
  
  # Exclude adaptive models in case still in list
  models= lapply(models, function(x) x[which(!grepl(pattern = "2", x = models$name))])

  
  # Compile models to avoid recompiling 
  models$compiled = sapply(1:length(models$stan.loglik), function(x) stan_model(file = models$stan.loglik[[x]], model_name = models$name[[x]]))

  
  # Results list
  results = list()
  
  # Create log file
  log.file = paste(paste("social/results/modelcomp_decpayoff/full_nonadaptive",                                  "log.txt", sep = "/"))
  if(!file.exists(log.file)){file.create(log.file)}
  
  # Loop over models
  for(mfit in 1:length(models$stan.loglik)){
    
    # Print info about current simulation / fitting to html
    # Print info about current simulation to html
    prgrss = paste("\n Currently fitting model", models$stan.loglik[[mfit]], "\n")
    write("", log.file, append = TRUE, ncolumns = 1)
    write(prgrss, log.file, append = TRUE, ncolumns = 1)

    # Fit model
    sink(log.file, append = T)
    fit = sampling(object = models$compiled[[mfit]], data = stan.data.d,
                   chains = chains, cores = cores, iter = iter, warmup = warmup, refresh = refresh)
    sink()
    saveRDS(fit, paste("social/results/modelcomp_decpayoff/full_nonadaptive", paste(models$name[[mfit]], "fit", "rds", sep = "."), sep = "/"))

    # Plot some diagnostics for population means
    diag.list = diagnostics.plot(model.fit = fit, plot.pars = names(models$free.pars.pop[[mfit]]))
    ggexport(plotlist = diag.list, width = 1920, height = 1080,
                   filename = paste("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "jpeg",  sep = "."), sep = "/"))
    
    # Plot detailed traceplots
    if(!dir.exists(
      paste("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics/detailed",models$name[[mfit]] , sep = "/"))){
      dir.create(paste("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics/detailed",models$name[[mfit]] , sep = "/"))
      }
    draws = tidy_draws(fit)
    par.names = names(draws)
    par.names = par.names[which(! names(draws) %in% c(".chain", ".iteration",".draw", "lp__",
                                                      "accept_stat__", "stepsize__",    "treedepth__",  "n_leapfrog__",
                                                      "divergent__",   "energy__"))]
    par.names = par.names[!grepl("log_lik", par.names)] 
    for (param in par.names) {
      tplot <- traceplot(fit, pars = param) + ggtitle(paste("Trace plot for", param))
      ggsave(paste("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics/detailed",models$name[[mfit]],  paste0("traceplot_", param, ".png"), sep = "/"), tplot)
    }
    
    # Save diagnostics for all parameters
    fit.summary = summary(fit)$summary
    write.csv(fit.summary, file = paste("social/results/modelcomp_decpayoff/full_nonadaptive/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "csv",  sep = "."), sep = "/"))
    
    # Print core diagnostics to log.txt
    # Extract effective sample size (ESS) and R-hat values
    ess <- fit.summary[, "n_eff"]
    rhat <- fit.summary[, "Rhat"]
    
    # Compute the required values
    num_low_ess <- sum(ess < 150, na.rm = TRUE)
    num_high_rhat <- sum(rhat > 1.01, na.rm = TRUE)
    min_ess <- min(ess, na.rm = TRUE)
    max_rhat <- max(rhat, na.rm = TRUE)
    
    # Prepare log message
    log_message <- sprintf(
      "Number of parameters with ESS < 150: %d\nNumber of parameters with Rhat > 1.01: %d\nLowest ESS: %.2f\nLargest Rhat: %.3f\n",
      num_low_ess, num_high_rhat, min_ess, max_rhat
    )
    write("", log.file, append = TRUE, ncolumns = 1)
    write(log_message, log.file, append = TRUE, ncolumns = 1)
    
    # Plot posterior
    draws = tidy_draws(fit) %>% select(names(models$free.pars.pop[[mfit]]))
    palpha = mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[grepl("alpha", names(models$free.pars.pop[[mfit]]))])
    pbeta= mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[!grepl("alpha", names(models$free.pars.pop[[mfit]]))])
    p = ggarrange(palpha, pbeta, ncol = 2)
    ggexport(p, width = 2550, height = 1440,
             filename = paste("social/results/modelcomp_decpayoff/full_nonadaptive", paste(models$name[[mfit]], "draws", "jpeg", sep = "."), sep = "/"))
  
    # Following is taken from http://mc-stan.org/loo/articles/loo2-with-rstan.html
    # Extract log likelihood values from model fit
    ll = extract_log_lik(fit, parameter_name = "log_lik", merge_chains = FALSE)
    remove(fit)

    # Drop log likelihood of observations that were set to 0 in stan (time == 0)
    indx = unique(which(ll != 0, arr.ind = T)[, 3])
    ll = ll[, , indx]

    # Compute relative effect sample sizes
    r_eff = relative_eff(exp(ll), cores = 2)

    # Compute psis loo
    loo.model = paste("loo", mfit, sep = ".")
    assign(loo.model, loo(ll, r_eff = r_eff, cores = 4))
    remove(ll)

    # Save diagnostics
    jpeg(paste("social/results/modelcomp_decpayoff/full_nonadaptive", paste(models$name[[mfit]], "paretok", "jpeg", sep = "."), sep = "/"))
    plot(get(loo.model))
    dev.off()

    sink(log.file, append = T)
    print(get(loo.model))
    sink()


    # Save to results
    results[[models$name[[mfit]]]] = get(loo.model)
    rm(list = loo.model)
    
  }
  
  # Compare models
  comparison = loo_compare(results)
  
  # Add model name
  comparison = as.data.frame(comparison)

  # Note winning model (to reload for parameter recovery)
  winner = comparison %>% filter(row_number() == 1 & elpd_diff == 0) %>% rownames() %>% unlist()
  
  # Save Variables
  save(results, comparison, winner, file = paste("social/results/modelcomp_decpayoff/full_nonadaptive", "modelcomp_decpayoff_full_nonadaptive.Rdata", sep = "/"))
  
  # Save and print comparison
  write.csv(x = comparison, file = paste("social/results/modelcomp_decpayoff/full_nonadaptive", "modelcomp_decpayoff_full_nonadaptive.csv", sep = "/"))
  
}else{
  
  # Read comparison
  load(file = paste("social/results/modelcomp_decpayoff/full_nonadaptive", "modelcomp_decpayoff_full_nonadaptive.Rdata", sep = "/"))
  
}

print(comparison[, ])

```

<!-- # Model comparison with only those (non-adaptive models) that build on the model winning in the location-only trials -->
<!-- ```{r, soc-model-parrecov_sub, echo=TRUE, results='markup'} -->

<!-- # Load winning model -->
<!-- load(file = paste("social/results/modelcomp_dec", "modelcomp_dec.Rdata", sep = "/")) -->
<!-- remove(results, comparison, comparison.named) -->

<!-- # # Parse name -->
<!-- # winner = gsub(pattern = ".hierarch", "", winner) -->
<!-- winner = "dbn" -->

<!-- # Get list of models -->
<!-- models = getmodels(hierarch = TRUE)  -->

<!-- # Index models -->
<!-- models = lapply(models, function(x) x[grepl(winner, models$name)]) -->

<!-- # Drop adaptive models in case they are still in the list -->
<!-- models = lapply(models, function(x) x[grepl("1", models$name)  | grepl("arl", models$name)]) -->
<!-- ``` -->

<!-- ```{r, run-modelcomp_decpay_sub, echo=TRUE, eval=TRUE} -->
<!-- if(!exists(paste("social/results/modelcomp_decpayoff_sub", "modelcomp_decpayoff_sub.Rdata", sep = "/"))){ -->

<!--   # Load winning model -->
<!--   load(file = paste("social/results/modelcomp_dec", "modelcomp_dec.Rdata", sep = "/")) -->
<!--   remove(results, comparison, comparison.named) -->

<!--   # # Parse name -->
<!--   # winner = gsub(pattern = ".hierarch", "", winner) -->
<!--   winner = "dbn" -->

<!--   # Get list of models -->
<!--   models = getmodels(hierarch = TRUE)  -->

<!--   # Index models -->
<!--   models = lapply(models, function(x) x[grepl(winner, models$name)]) -->

<!--   # Drop adaptive models in case they are still in the list -->
<!--   models = lapply(models, function(x) x[grepl("1", models$name)  | grepl("arl", models$name)]) -->

<!--   # Compile models to avoid recompiling  -->
<!--   models$compiled = sapply(1:length(models$stan.loglik), function(x) stan_model(file = models$stan.loglik[[x]], model_name = models$name[[x]])) -->

<!--   # Results list -->
<!--   results = list() -->

<!--   # Loop over models -->
<!--   for(mfit in 1:length(models$stan.loglik)){ -->

<!--     # Print info about current simulation / fitting to html -->
<!--     # Print info about current simulation to html -->
<!--     prgrss = paste("\n Currently fitting model", models$stan.loglik[[mfit]], "\n") -->


<!--     # Write log to text file fot when knitting -->
<!--     log.file = paste(paste("social/results/modelcomp_decpayoff_sub", -->
<!--                                     "log.txt", sep = "/")) -->
<!--     if(!file.exists(log.file)){file.create(log.file)} -->
<!--     write(prgrss, log.file, append = TRUE, ncolumns = 1) -->

<!--     # Fit model -->
<!--     sink(log.file, append = T) -->
<!--     fit = sampling(object = models$compiled[[mfit]], data = stan.data.d, -->
<!--                    chains = chains, cores = cores, iter = iter, warmup = warmup, refresh = refresh) -->
<!--     sink() -->
<!--     saveRDS(fit, paste("social/results/modelcomp_decpayoff_sub", paste(models$name[[mfit]], "fit", "rds", sep = "."), sep = "/")) -->

<!--     # Plot some diagnostics for population means -->
<!--     diag.list = diagnostics.plot(model.fit = fit, plot.pars = names(models$free.pars.pop[[mfit]])) -->
<!--     ggexport(plotlist = diag.list, width = 1920, height = 1080, -->
<!--                    filename = paste("social/results/modelcomp_decpayoff_sub/diagnostics", -->
<!--                                     paste(models$name[[mfit]], "diagnostics", "jpeg",  sep = "."), sep = "/")) -->

<!--     # Save diagnostics for all parameters -->
<!--     fit.summary = summary(fit)$summary -->
<!--     write.csv(fit.summary, file = paste("social/results/modelcomp_decpayoff_sub/diagnostics", -->
<!--                                     paste(models$name[[mfit]], "diagnostics", "csv",  sep = "."), sep = "/")) -->

<!--     # Plot posterior -->
<!--     draws = tidy_draws(fit) %>% select(names(models$free.pars.pop[[mfit]])) -->
<!--     palpha = mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[grepl("alpha", names(models$free.pars.pop[[mfit]]))]) -->
<!--     pbeta= mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[!grepl("alpha", names(models$free.pars.pop[[mfit]]))]) -->
<!--     p = ggarrange(palpha, pbeta, ncol = 2) -->
<!--     ggexport(p, width = 2550, height = 1440, -->
<!--              filename = paste("social/results/modelcomp_decpayoff_sub", paste(models$name[[mfit]], "draws", "jpeg", sep = "."), sep = "/")) -->

<!--     # Following is taken from http://mc-stan.org/loo/articles/loo2-with-rstan.html -->
<!--     # Extract log likelihood values from model fit -->
<!--     ll = extract_log_lik(fit, parameter_name = "log_lik", merge_chains = FALSE) -->
<!--     remove(fit) -->

<!--     # Drop log likelihood of observations that were set to 0 in stan (time == 0) -->
<!--     indx = unique(which(ll != 0, arr.ind = T)[, 3]) -->
<!--     ll = ll[, , indx] -->

<!--     # Compute relative effect sample sizes -->
<!--     r_eff = relative_eff(exp(ll), cores = 2) -->

<!--     # Compute psis loo -->
<!--     loo.model = paste("loo", mfit, sep = ".") -->
<!--     assign(loo.model, loo(ll, r_eff = r_eff, cores = 4)) -->
<!--     remove(ll) -->

<!--     # Save diagnostics -->
<!--     jpeg(paste("social/results/modelcomp_decpayoff_sub", paste(models$name[[mfit]], "paretok", "jpeg", sep = "."), sep = "/")) -->
<!--     plot(get(loo.model)) -->
<!--     dev.off() -->

<!--     sink(log.file, append = T) -->
<!--     print(get(loo.model)) -->
<!--     sink() -->


<!--     # Save to results -->
<!--     results[[mfit]] = get(loo.model) -->
<!--     rm(list = loo.model) -->

<!--   } -->

<!--   # Compare models -->
<!--   comparison = loo_compare(results) -->

<!--   # Add model name -->
<!--   comparison.rank = rownames(comparison) %>% parse_number() -->
<!--   comparison.named = as.data.frame(comparison) -->
<!--   comparison.named$modelname = sapply(comparison.rank, function(x) models$name[[x]]) -->

<!--   # Note winning model (to reload for parameter recovery) -->
<!--   winner = comparison.named %>% filter(row_number() == 1 & elpd_diff == 0) %>% select(modelname) %>% unlist() -->


<!--   # Save Variables -->
<!--   save(results, comparison, comparison.named, winner, file = paste("social/results/modelcomp_decpayoff_sub", "modelcomp_decpayoff_sub.Rdata", sep = "/")) -->

<!--   # Save and print comparison -->
<!--   write.csv(x = comparison, file = paste("social/results/modelcomp_decpayoff_sub", "modelcomp_decpayoff_sub.csv", sep = "/")) -->
<!--   write.csv(x = comparison.named, file = paste("social/results/modelcomp_decpayoff_sub", "modelcomp_decpayoff_sub_named.csv", sep = "/")) -->

<!-- }else{ -->

<!--   # Read comparison -->
<!--   load(file = paste("social/results/modelcomp_decpayoff_sub", "modelcomp_decpayoff_sub.Rdata", sep = "/")) -->

<!-- } -->

<!-- print(comparison[, ]) -->
<!-- print(comparison.named) -->

<!-- ``` -->

