---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Model Comparison
```{r setup-modcomp, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results = 'markup', warning = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(stringr)

library(ggplot2)
library(ggpubr)
library(viridis)

library(rstan)
library(loo)
library(tidybayes)
library(bayesplot)
library(randtoolbox)

# Source functions
setwd("~/Users/MarienhagenJonathan/rlforaging")

source("social/code/functions/softmax.R")
source("social/code/functions/diagnostics.plot.R")
source("social/code/functions/getmodels.R")



```
```{r, dir-modcomp, include=FALSE}
if(!dir.exists("social/results")){dir.create("social/results")}
if(!dir.exists("social/results/modelcomp_decpayoff")){dir.create("social/results/modelcomp_decpayoff")}
if(!dir.exists("social/results/modelcomp_decpayoff/diagnostics")){dir.create("social/results/modelcomp_decpayoff/diagnostics")}
```

## Experimental data
The following code snippet shows how the decision frequencies were computed
from the data.
```{r, data-modelcomp_dec, echo =TRUE, eval=TRUE}
# Read data
path = "~/Users/MarienhagenJonathan/thesisvc/data/data_discrete_1s.csv"
d = read.csv(path,colClasses = c(rep(NA, 8), rep("character", 2), rep(NA, 4)))

# Rename and add player id that is unique across sessions
d = d %>% mutate(decision = correct) %>% mutate(reward = catch) %>% mutate(nplayers = 5) %>%
  mutate(id = (session - 1) * 5  + player) %>% select(-player)

# Get socials trials with both observed decisions and observed payoffs
d = d %>% filter(social.fac == 3)

# Compute observed decisions and observed payoffs
d=d %>%
  arrange(session, trial, id, time.rounded) %>%
  # Observed decisions
  group_by(session, trial, id) %>%
  mutate(decision.lag = lag(decision)) %>%
  group_by(session, trial, time.rounded) %>%
  mutate(obs.dec.2 = sum(decision.lag)) %>% # Number of individuals choosing higher yielding patch
  ungroup() %>%
  mutate(obs.dec.2 = obs.dec.2 - decision.lag) %>% # Subtract individual's own choice
  ungroup() %>%
  mutate(obs.dec.1 = nplayers - 1 - obs.dec.2) %>% # Lower yielding patch
  mutate(obs.dec.1.norm = obs.dec.1 / (nplayers-1), obs.dec.2.norm = obs.dec.2 / (nplayers-1)) %>% # normalize
  relocate(obs.dec.1, obs.dec.2,.after = nplayers) %>%
  # Observed payoffs
  arrange(session, trial, id, time.rounded) %>%
  group_by(session, trial, id) %>%
  mutate(reward.lag = lag(reward)) %>% 
  group_by(session, trial, time.rounded, decision.lag) %>%
  mutate(obs.rew = sum(reward.lag)) %>% # Rewards obtained by all players at each patch
  group_by(session, trial, id) %>%
  mutate(obs.rew = obs.rew - reward.lag) %>% # Minus rewards obtained by individuals themselves
  mutate(obs.rew.norm = ifelse(decision.lag == 0, 
                               ifelse(obs.dec.1 == 0, 0, obs.rew / obs.dec.1),
                               ifelse(obs.dec.2 == 0, 0, obs.rew / obs.dec.2))) %>% # normalize
  mutate(decision = decision + 1) %>% # Transform [0, 1] to [1, 2]
  arrange(session, trial, id, time.rounded) 
  

# Account for missing social information for stan
d = d %>% 
  mutate(obs.dec.1.norm = ifelse(is.na(obs.dec.1.norm), 100, obs.dec.1.norm)) %>%
  mutate(obs.dec.2.norm = ifelse(is.na(obs.dec.2.norm), 100, obs.dec.2.norm)) %>%
  mutate(obs.rew.norm=ifelse(is.na(obs.rew.norm), 100, obs.rew.norm))

# Put experimental data in list
stan.data.d = with(d, list(
  OBSERVATIONS=nrow(d),
  SESSIONS=max(unique(session)), session=session,
  TRIALS=max(unique(trial)), trial=trial,
  MAXIMUM=length(unique(max.fac)), maximum=max.fac,
  RATIO=length(unique(ratio.fac)), ratio=ratio.fac,
  PLAYERS=unique(nplayers),
  ID=max(id), id=id,
  TIMES=max(unique(time.rounded)), time=time.rounded,
  DECISIONS=length(unique(decision)), decision=decision, 
  obsdec=cbind(obs.dec.1.norm, obs.dec.2.norm),
  obsrew=obs.rew.norm,
  REWARDS=length(unique(reward)), reward=reward
))
```


## MCMC Settings
Models were fitted with the following settings
```{r, mcmc-modelcomp_dec, echo=TRUE, results='markup'}
# MCMC 
chains = 4
cores = 4
iter = 3000
warmup = 2000
refresh = 100
```


### Model comparison 
```{r, run-modelcomp_dec, echo=TRUE, eval=TRUE}
if(!exists(paste("social/results/modelcomp_decpayoff", "modelcomp_decpayoff.Rdata", sep = "/"))){
  
  # Get models
  models = getmodels(hierarch = T)
  
  # Compile models to avoid recompiling 
  models$compiled = sapply(1:length(models$stan.loglik), function(x) stan_model(file = models$stan.loglik[[x]], model_name = models$name[[x]]))
  
  # Results list
  results = list()
  
  # Loop over models
  for(mfit in 1:length(models$stan.loglik)){
    
    # Print info about current simulation / fitting to html
    # Print info about current simulation to html
    prgrss = paste("\n Currently fitting model", models$stan.loglik[[mfit]], "\n")
  
  
    # Write log to text file fot when knitting
    log.file = paste(paste("social/results/modelcomp_decpayoff",
                                    "log.txt", sep = "/"))
    if(!file.exists(log.file)){file.create(log.file)}
    write(prgrss, log.file, append = TRUE, ncolumns = 1)

    # Fit model
    sink(log.file, append = T)
    fit = sampling(object = models$compiled[[mfit]], data = stan.data.d,
                   chains = chains, cores = cores, iter = iter, warmup = warmup, refresh = refresh)
    sink()
    saveRDS(fit, paste("social/results/modelcomp_decpayoff", paste(models$name[[mfit]], "fit", "rds", sep = "."), sep = "/"))

    # Plot some diagnostics for population means
    diag.list = diag.plot(model.fit = fit, plot.pars = names(models$free.pars.pop[[mfit]]))
    ggexport(plotlist = diag.list, width = 1920, height = 1080,
                   filename = paste("social/results/modelcomp_decpayoff/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "jpeg",  sep = "."), sep = "/"))

    # Save diagnostics for all parameters
    fit.summary = summary(fit)$summary
    write.csv(fit.summary, file = paste("social/results/modelcomp_decpayoff/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "csv",  sep = "."), sep = "/"))
    
    # Plot posterior
    draws = tidy_draws(fit) %>% select(names(models$free.pars.pop[[mfit]]))
    palpha = mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[grepl("alpha", names(models$free.pars.pop[[mfit]]))])
    pbeta= mcmc_areas(draws, pars = names(models$free.pars.pop[[mfit]])[!grepl("alpha", names(models$free.pars.pop[[mfit]]))])
    p = ggarrange(palpha, pbeta, ncol = 2)
    ggexport(p, width = 2550, height = 1440,
             filename = paste("social/results/modelcomp_decpayoff", paste(models$name[[mfit]], "draws", "jpeg", sep = "."), sep = "/"))
  
    # Following is taken from http://mc-stan.org/loo/articles/loo2-with-rstan.html
    # Extract log likelihood values from model fit
    ll = extract_log_lik(fit, parameter_name = "log_lik", merge_chains = FALSE)
    remove(fit)

    # Drop log likelihood of observations that were set to 0 in stan (time == 0)
    indx = unique(which(ll != 0, arr.ind = T)[, 3])
    ll = ll[, , indx]

    # Compute relative effect sample sizes
    r_eff = relative_eff(exp(ll), cores = 2)

    # Compute psis loo
    loo.model = paste("loo", mfit, sep = ".")
    assign(loo.model, loo(ll, r_eff = r_eff, cores = 4))
    remove(ll)

    # Save diagnostics
    jpeg(paste("social/results/modelcomp_decpayoff", paste(models$name[[mfit]], "paretok", "jpeg", sep = "."), sep = "/"))
    plot(get(loo.model))
    dev.off()

    sink(log.file, append = T)
    print(get(loo.model))
    sink()


    # Save to results
    results[[mfit]] = get(loo.model)
    rm(list = loo.model)
    
  }
  
  # Compare models
  comparison = loo_compare(results)
  
  # Add model name
  comparison.rank = rownames(comparison) %>% parse_number()
  comparison.named = as.data.frame(comparison)
  comparison.named$modelname = sapply(comparison.rank, function(x) models$name[[x]])
  
  # Note winning model (to reload for parameter recovery)
  winner = comparison.named %>% filter(row_number() == 1 & elpd_diff == 0) %>% select(modelname) %>% unlist()
  
  
  # Save Variables
  save(results, comparison, comparison.named, winner, file = paste("social/results/modelcomp_decpayoff", "modelcomp_decpayoff.Rdata", sep = "/"))
  
  # Save and print comparison
  write.csv(x = comparison, file = paste("social/results/modelcomp_decpayoff", "modelcomp_decpayoff.csv", sep = "/"))
  write.csv(x = comparison.named, file = paste("social/results/modelcomp_decpayoff", "modelcomp_decpayoff_named.csv", sep = "/"))
  
}else{
  
  # Read comparison
  load(file = paste("social/results/modelcomp_decpayoff", "modelcomp_decpayoff.Rdata", sep = "/"))
  
}

print(comparison[, ])
print(comparison.named)


# # Test
# k = bind_cols(stan.data.d) %>% 
#   filter(time != 0) %>%
#   cbind(ARL = loo.1[["pointwise"]][, 5]) %>%
#   cbind(DB1 = loo.2[["pointwise"]][, 5]) %>%
#   cbind(DB2 = loo.3[["pointwise"]][, 5]) %>%
#   cbind(VS1 = loo.4[["pointwise"]][, 5]) %>%
#   cbind(VS2 = loo.5[["pointwise"]][, 5]) %>%
#   pivot_longer(c(ARL, DB1, DB2, VS1, VS2), names_to = "model", values_to ="paretok")
# 
# k %>%
#   group_by(ratio, maximum, model) %>%
#   mutate(bad = ifelse(paretok >= .7, 1, 0)) %>%
#   reframe(n = sum(bad) / (nrow(k))) %>%
#   ggplot(aes(x=ratio, y=n, col=as.factor(maximum), group=as.factor(maximum))) + geom_point() + geom_line()+
#   facet_wrap(~ model, scales = "free")
# 
# k %>%
#   group_by(id, model) %>%
#   mutate(bad = ifelse(paretok >= .7, 1, 0)) %>%
#   reframe(n = sum(bad) / (nrow(k))) %>%
#   ggplot(aes(x=id, y=n)) + geom_point() +
#   facet_wrap(~ model, scales = "free")
# 
# k %>% filter(model=="VS2") %>%
#   mutate(obsdec.1 = obsdec[, 1], obsdec.2 = obsdec[, 2]) %>% select(-obsdec) %>%
#   group_by(obsdec.2, ratio, maximum, model) %>%
#   mutate(bad = ifelse(paretok >= .7, 1, 0)) %>%
#   reframe(n = sum(bad) / (nrow(k)))  %>%
#   ggplot(aes(x=obsdec.2, y=n, col=model)) + geom_point() +
#   facet_grid(ratio ~ maximum)
# 
# 
# k %>% filter(model == "VS2") %>%
#   mutate(obsdec.1 = obsdec[, 1], obsdec.2 = obsdec[, 2]) %>% select(-obsdec) %>%
#   mutate(maj = ifelse(obsdec.1 == obsdec.2, 0, 
#                       ifelse(obsdec.1 < obsdec.2, -1, 1))) %>%
#   #mutate(conf = ifelse(maj-1 == decision, 0, 1)) %>%
#   group_by(maj, ratio, maximum, model) %>%
#   mutate(bad = ifelse(paretok >= .7, 1, 0)) %>%
#   reframe(n = sum(bad) / (nrow(k)))  %>%
#   ggplot(aes(x=maj, y=n, col=model)) + geom_point() +
#   facet_grid(ratio ~ maximum)

```
