---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Model Comparison
```{r setup-asoc-model_comp, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results = 'markup', warning = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(stringr)

library(ggplot2)
library(ggpubr)
library(viridis)

library(rstan)
library(loo)
library(tidybayes)
library(bayesplot)
library(randtoolbox)

# Set wd
setwd("~/Users/MarienhagenJonathan/rlforaging")

# Source functions
setwd("~/Users/MarienhagenJonathan/rlforaging")
function.list = paste0("asocial/code/functions/", list.files("asocial/code/functions"))
function.list = function.list[sapply(function.list, function(x) !grepl("2", x))]
sapply(function.list, source, .GlobalEnv)


```
```{r, dir-modcomp, include=FALSE}
if(!dir.exists("asocial/results")){dir.create("asocial/results")}
if(!dir.exists("asocial/results/modelcomp")){dir.create("asocial/results/modelcomp")}
if(!dir.exists("asocial/results/modelcomp/diagnostics")){dir.create("asocial/results/modelcomp/diagnostics")}
```

## Experimental data
Load experimental data
```{r, experiment-asoc_modelcomp, echo =TRUE, eval=TRUE}

# Read data
path = "~/Users/MarienhagenJonathan/thesisvc/data/data_discrete_1s.csv"
d = read.csv(path,colClasses = c(rep(NA, 8), rep("character", 2), rep(NA, 4)))

# Set player id unique across sessions
d = d %>% mutate(id = (session - 1) * 5  + player) %>% select(-player)

# Get solo trials
d = d %>% filter(social.fac == 1)

# Transform
d=d %>%
  mutate(decision = correct) %>% mutate(reward = catch) %>% mutate(nplayers = 5) %>%
  mutate(decision = decision + 1) # Transform [0, 1] to [1, 2]

# Put experimental data in list
stan.data.d = with(d, list(
  OBSERVATIONS=nrow(d),
  SESSIONS=max(unique(session)), session=session,
  TRIALS=max(unique(trial)), trial=trial,
  MAXIMUM=length(unique(max.fac)), maximum=max.fac,
  RATIO=length(unique(ratio.fac)), ratio=ratio.fac,
  PLAYERS=unique(nplayers),
  ID=max(id), id=id,
  TIMES=max(unique(time.rounded)), time=time.rounded,
  DECISIONS=length(unique(decision)), decision=decision, 
  REWARDS=length(unique(reward)), reward=reward
))
```


## MCMC Settings
Models were fitted with the following settings
```{r, mcmc-asoc_modelcomp, echo=TRUE, results='markup'}
# MCMC 
chains = 4
cores = 4
iter = 2000
warmup = 1000
refresh = 100
```


## Model comparison 
The following code snippets show how the model comparison was computed. (Diagnostics
are save to the results folder so be sure to check them.)
```{r, compute-asoc-model_comp, echo=TRUE}
# Manual caching to avoid recomputing everything when rendering the html

if(!file.exists("asocial/results/modelcomp/modelcomp.Rdata")){
  
  models = getmodels(hierarch = T)

  # Compile models to avoid recompiling 
  models$compiled = sapply(1:length(models$stan.loglik), function(x) stan_model(file = models$stan.loglik[[x]], model_name = models$name[[x]]))
  
  # Results list
  results = list()
  
  # Loop over models
  for(mfit in 1:length(models$stan.loglik)){
    
    # Print info about current simulation / fitting to html
    # Print info about current simulation to html
    prgrss = paste("Currently fitting model", models$name[[mfit]])
  
  
    # Write log to text file fot when knitting
    log.file = paste(paste("asocial/results/modelcomp", "log.txt", sep = "/"))
    if(!file.exists(log.file)){file.create(log.file)}
    write(prgrss, log.file, append = TRUE, ncolumns = 1)
  
    # Fit model
    fit = sampling(object = models$compiled[[mfit]], data = stan.data.d, 
                   chains = chains, cores = cores, iter = iter, warmup = warmup, refresh = refresh)
    saveRDS(fit, paste("asocial/results/modelcomp", paste(models$name[[mfit]], "fit", "rds", sep = "."), sep = "/"))
  
    # Plot some diagnostics for population means
    diagnostics.list = diagnostics.plot(model.fit = fit, plot.pars = names(models$free.pars.pop[[mfit]]))
    ggexport(plotlist = diagnostics.list, width = 1920, height = 1080,
                   filename = paste("asocial/results/modelcomp/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "jpeg",  sep = "."), sep = "/"))
    
    # Save diagnostics for all parameters 
    fit.summary = summary(fit)$summary
    write.csv(fit.summary, file = paste("asocial/results/modelcomp/diagnostics",
                                    paste(models$name[[mfit]], "diagnostics", "csv",  sep = "."), sep = "/"))
    
  
    # Following is taken from http://mc-stan.org/loo/articles/loo2-with-rstan.html
    # Extract log likelihood values from model fit
    ll = extract_log_lik(fit, parameter_name = "log_lik", merge_chains = FALSE)
  
    # Drop log likelihood of observations that were set to 0 in stan (time == 0)
    indx = unique(which(ll != 0, arr.ind = T)[, 3])
    ll = ll[, , indx]
  
    # Compute relative effect sample sizes
    r_eff = relative_eff(exp(ll), cores = 2)
  
    # Compute psis loo 
    loo.model = paste("loo", mfit, sep = ".")
    assign(loo.model, loo(ll, r_eff = r_eff, cores = 4))
    remove(ll)
    
    # Save diagnostics
    jpeg(paste("asocial/results/modelcomp", paste(models$name[[mfit]], "paretok", "jpeg", sep = "."), sep = "/"),
         width = 2550, height = 1440, units = "px")
    plot(get(loo.model))
    dev.off()

    sink(log.file, append = T)
    print(get(loo.model))
    sink()
  
  
    # Save to results
    results[[mfit]] = get(loo.model)
    rm(list = loo.model)
    
  }
  
  # Compare models
  comparison = loo_compare(results)
  
  # Add model name
  comparison.rank = rownames(comparison) %>% parse_number()
  comparison.named = as.data.frame(comparison)
  comparison.named$modelname = sapply(comparison.rank, function(x) models$name[[x]])
  
  # Note winning model (to reload for parameter recovery)
  winner = comparison.named %>% filter(row_number() == 1 & elpd_diff == 0) %>% select(modelname) %>% unlist()
  
  
  # Save Variables
  save(list=c("results", "comparison", "comparison.named", "winner"), file = paste("asocial/results/modelcomp", "modelcomp.Rdata", sep = "/"))
  
  # Save and print comparison
  write.csv(x = comparison, file = paste("asocial/results/modelcomp", "modelcomp.csv", sep = "/"))
  write.csv(x = comparison.named, file = paste("asocial/results/modelcomp", "modelcompnamed.csv", sep = "/"))
  
}else{
  
  # Read comparison
  load(file = paste("asocial/results/modelcomp", "modelcomp.Rdata", sep = "/"))
  
}

print(comparison[, ])
print(comparison.named)
```

## Posterior predictions

```{r, postpred-asoc, echo=TRUE}

# Get initial distribution of players from data
decfreq.init = d %>% filter(time.rounded == 0) %>% select(id, max, max.fac, ratio, ratio.fac, decision)

# Number of times experiments were simulated from each model
nsim=25

# Experimental parameters (identical for all simulations)
exp.pars = list(
  sessions = 18,
  trials = 12,
  nplayers = 5, # number of players per session
  durations.vec = c(75)  # The simulation functions sample trial lengths from this vector (equally) 
                                  # and randomly assigns them to the different environments
)
# Add unique ids for players (rows are sessions)
exp.pars$id = with(exp.pars, matrix(1:(sessions*nplayers), ncol=nplayers, byrow = T))

# Environmental parameters (identical for all simulations)
max = round(c(.5, .7, .9), digits = 2)
ratio = round(c(.5, .65, .8, .95), digits = 2)
env.pars = expand.grid(max=max, ratio=ratio)
env.pars = list(max=env.pars$max, ratio=env.pars$ratio)

# Set the winning model / the best, simplest model
winner = "m4.1"
winnerindx = which(models$name == winner)

# Index model in list
models = getmodels(hierarch = F)
models = lapply(models, function(x) x[which(models$name %in% winner)])

# Load fit
fit = readRDS(paste("asocial/results/modelcomp", paste(winner, "fit", "rds", sep = "."), sep = "/"))

# Extract draws
draws = tidy_draws(fit)
rl.pars = draws[, names(draws) %in% names(models$free.pars[[1]])] 
rl.pars = apply(rl.pars, 2, mean)
rl.pars = append(rl.pars, models$fixed.pars[[winnerindx]])
  
# Prep simulation
f = get(models$sim[[winnerindx]])
sim.pars = c(exp.pars, env.pars, rl.pars, list(decfreq.init))

# Simulate
results = list()
for(sim in 1:nsim){
  print(paste("Simulation", sim, "of", nsim))
  sim.data = f(sim.parameters = sim.pars, postpredict = T) %>% mutate(sim=sim, decision = decision - 1)
  results[[sim]] = sim.data
  
}
results = bind_rows(results)

# Summarise simulated data
plot.data = results %>%
  group_by(sim, time, ratio, max) %>% 
  reframe(acc = mean(decision))  %>%
  group_by(time, ratio, max) %>%
  reframe(mu =mean(acc), se = sd(acc) / sqrt(nsim)) %>%
  mutate(lower = mu - se, upper = mu + se)

write.csv(plot.data, file = paste("asocial", "results", "modelcomp", "postpredict_alone.csv", sep = "/"))

# Plot posterior means + hdis 
ratio.labs = paste("Catch Ratio:", sort(unique(plot.data$ratio)))
names(ratio.labs) = sort(unique(plot.data$ratio))

max.labs = paste("Max Catch", sort(unique(plot.data$max)))
names(max.labs) = sort(unique(plot.data$max))

facet.labeller = labeller(ratio.fac = ratio.labs, max.fac = max.labs)

plot.data %>% 
  ggplot(aes(x=time, y=mu, ymin=lower, ymax=upper, col=as.factor(max), fill=as.factor(max))) +
  scale_color_viridis(name="Max Catch", discrete = T) +
  scale_fill_viridis(name="Max Catch", discrete = T)+
  ylim(0, 1) +
  geom_ribbon(alpha=.5) +
  geom_line() +
  geom_hline(yintercept = .5, lty=2) +
  theme_linedraw(base_size = 11) +
  theme(text = element_text(size=rel(5)),
        strip.text.x = element_text(size=rel(7)),
        strip.text.y = element_text(size=rel(7)), 
        axis.text.x = element_text(size=rel(7)),
        axis.title.x = element_text(size=rel(7)),
        axis.text.y = element_text(size=rel(7)),
        axis.title.y = element_text(size=rel(7)),
        legend.text = element_text(size=rel(7)), 
        legend.title = element_text(size=rel(7)),
        plot.title = element_text(hjust = 0.5, size = rel(8)),
        plot.margin = margin(1,1,1,1, "cm")) +
  labs(x="Time", y="Mean Accuracy \n", 
       col="Probability Maximum") +
  facet_wrap( ~ ratio, ncol=4, labeller = facet.labeller)





```