---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Asocial Model Recovery
```{r setup-asoc-modrecov, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, results = 'markup', warning = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(readr)
library(stringr)

library(ggplot2)
library(ggpubr)
library(viridis)

library(rstan)
library(loo)
library(tidybayes)
library(bayesplot)
library(randtoolbox)

# Set wd
setwd("~/Users/MarienhagenJonathan/rlforaging")

source("asocial/code/functions/softmax.R")
source("asocial/code/functions/diagnostics.plot.R")
source("asocial/code/functions/plot.par.recov.R")
source("asocial/code/functions/getmodels.R")
source("asocial/code/functions/m1.1.fixed.sim.R")
source("asocial/code/functions/m2.1.fixed.sim.R")
source("asocial/code/functions/m3.1.fixed.sim.R")
source("asocial/code/functions/m4.1.fixed.sim.R")
source("asocial/code/functions/m4.2.fixed.sim.R")
source("asocial/code/functions/m4.3.fixed.sim.R")


```
```{r, dir-asoc-modrecov, include=FALSE}
if(!dir.exists("asocial/results")){dir.create("asocial/results")}
if(!dir.exists("asocial/results/modelrecov")){dir.create("asocial/results/modelrecov")}
if(!dir.exists("asocial/results/modelrecov/diagnostics")){dir.create("asocial/results/modelrecov/diagnostics")}
```

## Synthetic Data
```{r, sim-asoc-modrecov, echo = T, results='markup'}

# Number of times experiments were simulated from each model
nsim=10

# Experimental parameters (identical for all simulations)
exp.pars = list(
  sessions = 18,
  trials = 12,
  nplayers = 5, # number of players per session
  durations.vec = c(75, 90, 105)  # The simulation functions sample trial lengths from this vector (equally) 
                                  # and randomly assigns them to the different environments
)
# Add unique ids for players (rows are sessions)
exp.pars$id = with(exp.pars, matrix(1:(sessions*nplayers), ncol=nplayers, byrow = T))

# Environmental parameters (identical for all simulations)
max = c(.5, .7, .9)
ratio = c(.5, .65, .8, .95)
env.pars = expand.grid(max=max, ratio=ratio)
env.pars = list(max=env.pars$max, ratio=env.pars$ratio)

```

## Stan
Parameters were estimated with the following settings.
```{r, mcmc-asoc-modrecov, echo=T}
# MCMC
MCMC = list(chains = 4, cores = 4, iter = 100, warmup = 50, refresh = 1)
```

## Model Recovery

```{r, asoc-modrecov, echo=TRUE, eval=TRUE,  fig.width=24, fig.height=13.5}
# Manual caching to avoid recomputing
if(!exists(paste("asocial/results/modelrecov", "modrecov.rds", sep = "/"))){
  
  # Get model list
  models = getmodels(hierarch = F)
  
  # Compile the loglik models to avoid recompiling when looping over different models to fit
  models$compiledloglik = sapply(1:length(models$stan.loglik), function(x)
    stan_model(file = models$stan.loglik[[x]], model_name = models$name[[x]]))
    
  # Read data
  path = "~/Users/MarienhagenJonathan/thesisvc/data/data_discrete_1s.csv"
  d = read.csv(path,colClasses = c(rep(NA, 8), rep("character", 2), rep(NA, 4)))
  
  # Set player id unique across sessions
  d = d %>% mutate(player = (session - 1) * 5  + player)
  
  # Get solo trials
  d = d %>% filter(social.fac == 1)
  
  # Transform
  d=d %>%
    mutate(decision = correct) %>% mutate(reward = catch) %>% mutate(nplayers = 5) %>%
    mutate(decision = decision + 1) # Transform [0, 1] to [1, 2]
  
  # Put experimental data in list
  stan.data.d = with(d, list(
    OBSERVATIONS=nrow(d),
    SESSIONS=max(unique(session)), session=session,
    TRIALS=max(unique(trial)), trial=trial,
    MAXIMUM=length(unique(max.fac)), maximum=max.fac,
    RATIO=length(unique(ratio.fac)), ratio=ratio.fac,
    PLAYERS=unique(nplayers),
    TIMES=max(unique(time.rounded)), time=time.rounded,
    DECISIONS=length(unique(decision)), decision=decision, 
    REWARDS=length(unique(reward)), reward=reward
  ))

  
  # Global comparison list to save data to
  comp.global = list(msim = c(), sim = c(), mfit = c(), win = c())
  
  # Loop over simulating model
  for(msim in 1:length(models$name)){
      
    # Fit model to the experimental data (non log like version)
    fit = stan(file = models$stan[[msim]], data = stan.data.d,
               chains = MCMC$chains, cores = MCMC$cores, iter = MCMC$iter, warmup = MCMC$warmup, refresh=MCMC$refresh)
    saveRDS(fit, file = paste("asocial/results/modelrecov", paste(models$name[[msim]], "fit", "rds", sep = "."), sep = "/"))
    
    # Get rl pars
    draws = tidy_draws(fit) %>% select(names(models$free.pars[[msim]]))
    rl.pars = draws[sample(1:nrow(draws), size = nsim, replace = F), ]
    
    # Account for different variable types when nsim == 1 or > 1
    # if(nsim == 1){rl.pars = t(rl.pars)}else{rl.pars = rl.pars}
    
    # Add fixed pars
    rl.pars = rl.pars %>%
      cbind(models$fixed.pars[[msim]])
    
    # Save generating pars in case we need to diagnose problems
    write_csv(rl.pars, file = paste("asocial/results/modelrecov/diagnostics", paste(models$name[[msim]], "rlpars", "csv", sep = "."), sep = "/"))
    
    # Get simulation function
    f = get(models$sim[[msim]])
    
    # Loop over simulations
    for(sim in 1:nsim){
      
      # Check if there are any nested parameters
      if(any(sapply(models$free.pars.struct[[msim]], function(x) is.list(x)))){
        
        # Get nested lists in models free pars (pars with offsets)
        indx = sapply(models$free.pars.struct[[msim]], function(x) is.list(x))
        indx = indx[indx == TRUE]
        
        # "Unpack" nested list index to index rl.pars data frame
        indx.df = lapply(names(indx), function(x) grepl(x, names(rl.pars)))
        names(indx.df) = names(indx)
        
        
        # Get rl.pars and add to sim pars
        sim.pars = c(exp.pars, env.pars,
                     lapply(indx.df, function(x) matrix(data = rl.pars[sim, x], nrow = length(unique(max)))), # nested pars
                     rl.pars[sim, which(!apply(as.data.frame(indx.df), 1, any))] # non-nested pars
        )
        
        # Unlist individual learning rates
        if(models$name[[mod]] != "m4.3"){
          sim.pars$alphaQN = unlist(sim.pars$alphaQN)
          sim.pars$alphaQP = unlist(sim.pars$alphaQP)
        }
      }else{
        # Get rl.pars and add to sim pars
        sim.pars = c(exp.pars, env.pars, rl.pars[sim, ])
      }
      
      # Simulate data
      sim.data = f(sim.parameters = sim.pars)
      
      # Put data in list
      stan.data.sim = with(sim.data, list(
        OBSERVATIONS=nrow(sim.data),
        SESSIONS=max(unique(session)), session=session,
        TRIALS=max(unique(trial)), trial=trial,
        MAXIMUM=length(unique(max.fac)), maximum=max.fac,
        RATIO=length(unique(ratio.fac)), ratio=ratio.fac,
        PLAYERS=unique(nplayers),
        TIMES=max(unique(time)), time=time,
        DECISIONS=length(unique(decision)), decision=decision, 
        REWARDS=length(unique(reward)), reward=reward
      ))
      
      # Local comparison list to save psis to for each model fit
      comp.local = list()
      
      # Loop over fitting models
      for(mfit in 1:length(models$name)){
        
        # Print info about progress to log.txt
        prgrss = paste("Data simulated from", models$name[[msim]],  
                       "Currently fitting model", models$stan[[mfit]])
        
        # Create log file
        logfile = "asocial/results/modelrecov/log.txt"
        if(!file.exists(logfile)){file.create(logfile)}

        #Open connection to file
        logcon = file(logfile, open = "at")
        
        # Print progress
        sink(file = logcon, append = T)
        print(prgrss)
        sink()
        
        # Close connection to file
        close(logcon)
        
        
        # Fit model
        fit = sampling(object = models$compiledloglik[[mfit]], data = stan.data.sim,
                       chains = MCMC$chains, cores = MCMC$cores, iter = MCMC$iter, warmup = MCMC$warmup, refresh = MCMC$refresh)
        
        # Plot and save some diagnostics
        diag.list = diag.plot(model.fit = fit, plot.pars = names(models$free.pars[[mfit]]))
        ggexport(plotlist = diag.list, width = 1920, height = 1080,
                 filename = paste("asocial/results/modelrecov/diagnostics",
                                  paste(
                                    paste(models$name[[msim]], "sim", sim, "fit", models$name[[mfit]], "diagnostics",  sep = "_"), "jpeg", sep = "."),
                                  sep = "/"))
        
        # Compute psis
        # Following is taken from http://mc-stan.org/loo/articles/loo2-with-rstan.html
        
        # Extract log likelihood values from model fit
        ll = extract_log_lik(fit, parameter_name = "log_lik", merge_chains = FALSE)
        
        # Drop log likelihood of observations that were set to 0 in stan (time == 0)
        indx = unique(which(ll != 0, arr.ind = T)[, 3])
        ll = ll[, , indx]
        
        # Compute relative effect sample sizes
        r_eff = relative_eff(exp(ll), cores = 2)
        
        # Compute psis loo 
        loo.model = paste("loo", models$name[[mfit]], sep = ".")
        assign(loo.model, loo(ll, r_eff = r_eff, cores = 4))
        remove(ll)
        
        # Save to results
        comp.local[[mfit]] = get(loo.model)
        
        # Save diagnostics
        jpeg(paste("asocial/results/modelrecov/diagnostics",
                                  paste(
                                    paste(models$name[[msim]], "sim", sim, "fit", models$name[[mfit]], "paretok",  sep = "_"), "jpeg", sep = "."),
                                  sep = "/"),
             width = 2550, height = 1440, units = "px")
        plot(get(loo.model))
        dev.off()
      
        #Open connection to file
        logcon = file(logfile, open = "at")
        
        # Print loo summary
        sink(logcon, append = T)
        print(get(loo.model))
        sink()
        
        # Close connection to file
        close(logcon)
        
      } # Close loop over fitting models
      
      # Compare all model fits for current simulation from current simulating model
      comp.local = loo_compare(comp.local)
      
      # Get winning model (Number represents position in models list)
      comp.local = names(which(comp.local[, "elpd_diff"] == 0)) %>% parse_number()
      
      # Vector representing fitted models with 1 == win and 0 == loss
      win = rep(0, length(models$name))
      win[comp.local] = 1
      
      # Append: simulating model, simulation, fitted model and whether fitted model won or not
      comp.global$msim = append(comp.global$msim, rep(msim, length(models$name)))
      comp.global$sim = append(comp.global$sim, rep(sim, length(models$name)))
      comp.global$mfit = append(comp.global$mfit, 1:length(models$name))
      comp.global$win = append(comp.global$win, win)
    }
  }
  
  # Save comp.global list
  saveRDS(c(models, comp.global), file = paste("asocial/results/modelrecov", "modrecov.rds", sep = "/"))
  
  # For each simulated model, count how often the other models won the comparison
  comp.global = bind_cols(comp.global) %>%
    group_by(msim, mfit) %>%
    reframe(p = sum(win) / nsim) %>%
    mutate(msim = factor(msim, labels = unlist(models$name))) %>%
    mutate(mfit = factor(mfit, labels = unlist(models$name)))
  
}else{ # if not recomputing, load model recovery
  
  comp.global = readRDS(file = paste("asocial/results/modelrecov", "modrecov.rds", sep = "/"))
  
  # For each simulated model, count how often the other models won the comparison
  comp.global = bind_cols(comp.global) %>%
    group_by(msim, mfit) %>%
    reframe(p = sum(win) / nsim) %>%
    mutate(msim = factor(msim, labels = unlist(models$name))) %>%
    mutate(mfit = factor(mfit, labels = unlist(models$name)))
  
}

# Plot confusion matrix
p = comp.global %>%
  ggplot(aes(x=mfit, y=msim, fill=p)) +
  geom_tile(alpha=.75, col="black", size=1) +
  geom_text(aes(label=p), size=10) +
  labs(x="Fitted Model", y="Simulated Model", fill="p(fit|sim) \n") +
  scale_fill_viridis()+
  theme_gray(base_size = 11) +
    theme(text = element_text(size=rel(5)),
          plot.title = element_text(hjust = 0.5, size = rel(8)),
          strip.text = element_text(size = rel(5)),
          legend.text = element_text(size=rel(2.5)),
          legend.key.size = unit(2, "cm"),
          plot.margin = margin(1,1,1,1, "cm"))
print(p)
ggexport(p, width = 2560, height = 1440, 
         filename = paste("asocial/results/modelrecov", "modelrecov.jpeg", sep = "/"))
  

```